linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 40
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gocyclo
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - gofmt
    - forbidigo
    # don't enable:
    # - depguard
    # - asciicheck
    # - scopelint
    # - gochecknoglobals
    # - gocognit
    # - godot
    # - godox
    # - goerr113
    # - interfacer
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - revive
    # - wsl
    # ###
    # - stylecheck
    # - errcheck
    # - gomnd
    # - gocritic
    # - lll
    # TODO
    # - noctx
    # - whitespace
    # - unparam
    # - golint
    # - gochecknoinits
    # - goconst
    # - dupl
    # - funlen
    # - exhaustive
    # - gosec
    # - nakedret
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
run:
  go: "1.18"
  timeout: 30m
  issue-exit-code: 1
  tests: false
  skip-dirs:
    - "integrationtest"
    - "rdbtest"
  skip-files:
    - ".*asset.go"
    - ".*statik.go"
