repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: "CREDITS"
    -   id: trailing-whitespace
        exclude: "CREDITS"
    -   id: check-merge-conflict
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.12.0
  hooks:
    - id: gitleaks
- repo: https://github.com/golangci/golangci-lint
  rev: v1.49.0
  hooks:
    - id: golangci-lint
