// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package iscp2

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Message:
	//	*Message_ConnectRequest
	//	*Message_ConnectResponse
	//	*Message_Disconnect
	//	*Message_UpstreamOpenRequest
	//	*Message_UpstreamOpenResponse
	//	*Message_UpstreamResumeRequest
	//	*Message_UpstreamResumeResponse
	//	*Message_UpstreamCloseRequest
	//	*Message_UpstreamCloseResponse
	//	*Message_UpstreamChunk
	//	*Message_UpstreamChunkAck
	//	*Message_UpstreamMetadata
	//	*Message_UpstreamMetadataAck
	//	*Message_DownstreamOpenRequest
	//	*Message_DownstreamOpenResponse
	//	*Message_DownstreamResumeRequest
	//	*Message_DownstreamResumeResponse
	//	*Message_DownstreamCloseRequest
	//	*Message_DownstreamCloseResponse
	//	*Message_DownstreamChunk
	//	*Message_DownstreamChunkAck
	//	*Message_DownstreamChunkAckComplete
	//	*Message_DownstreamMetadata
	//	*Message_DownstreamMetadataAck
	//	*Message_Ping
	//	*Message_Pong
	//	*Message_UpstreamCall
	//	*Message_UpstreamCallAck
	//	*Message_DownstreamCall
	Message              isMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Message interface {
	isMessage_Message()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,1,opt,name=connect_request,json=connectRequest,proto3,oneof" json:"connect_request,omitempty"`
}
type Message_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,2,opt,name=connect_response,json=connectResponse,proto3,oneof" json:"connect_response,omitempty"`
}
type Message_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,3,opt,name=disconnect,proto3,oneof" json:"disconnect,omitempty"`
}
type Message_UpstreamOpenRequest struct {
	UpstreamOpenRequest *UpstreamOpenRequest `protobuf:"bytes,64,opt,name=upstream_open_request,json=upstreamOpenRequest,proto3,oneof" json:"upstream_open_request,omitempty"`
}
type Message_UpstreamOpenResponse struct {
	UpstreamOpenResponse *UpstreamOpenResponse `protobuf:"bytes,65,opt,name=upstream_open_response,json=upstreamOpenResponse,proto3,oneof" json:"upstream_open_response,omitempty"`
}
type Message_UpstreamResumeRequest struct {
	UpstreamResumeRequest *UpstreamResumeRequest `protobuf:"bytes,66,opt,name=upstream_resume_request,json=upstreamResumeRequest,proto3,oneof" json:"upstream_resume_request,omitempty"`
}
type Message_UpstreamResumeResponse struct {
	UpstreamResumeResponse *UpstreamResumeResponse `protobuf:"bytes,67,opt,name=upstream_resume_response,json=upstreamResumeResponse,proto3,oneof" json:"upstream_resume_response,omitempty"`
}
type Message_UpstreamCloseRequest struct {
	UpstreamCloseRequest *UpstreamCloseRequest `protobuf:"bytes,68,opt,name=upstream_close_request,json=upstreamCloseRequest,proto3,oneof" json:"upstream_close_request,omitempty"`
}
type Message_UpstreamCloseResponse struct {
	UpstreamCloseResponse *UpstreamCloseResponse `protobuf:"bytes,69,opt,name=upstream_close_response,json=upstreamCloseResponse,proto3,oneof" json:"upstream_close_response,omitempty"`
}
type Message_UpstreamChunk struct {
	UpstreamChunk *UpstreamChunk `protobuf:"bytes,70,opt,name=upstream_chunk,json=upstreamChunk,proto3,oneof" json:"upstream_chunk,omitempty"`
}
type Message_UpstreamChunkAck struct {
	UpstreamChunkAck *UpstreamChunkAck `protobuf:"bytes,71,opt,name=upstream_chunk_ack,json=upstreamChunkAck,proto3,oneof" json:"upstream_chunk_ack,omitempty"`
}
type Message_UpstreamMetadata struct {
	UpstreamMetadata *UpstreamMetadata `protobuf:"bytes,72,opt,name=upstream_metadata,json=upstreamMetadata,proto3,oneof" json:"upstream_metadata,omitempty"`
}
type Message_UpstreamMetadataAck struct {
	UpstreamMetadataAck *UpstreamMetadataAck `protobuf:"bytes,73,opt,name=upstream_metadata_ack,json=upstreamMetadataAck,proto3,oneof" json:"upstream_metadata_ack,omitempty"`
}
type Message_DownstreamOpenRequest struct {
	DownstreamOpenRequest *DownstreamOpenRequest `protobuf:"bytes,128,opt,name=downstream_open_request,json=downstreamOpenRequest,proto3,oneof" json:"downstream_open_request,omitempty"`
}
type Message_DownstreamOpenResponse struct {
	DownstreamOpenResponse *DownstreamOpenResponse `protobuf:"bytes,129,opt,name=downstream_open_response,json=downstreamOpenResponse,proto3,oneof" json:"downstream_open_response,omitempty"`
}
type Message_DownstreamResumeRequest struct {
	DownstreamResumeRequest *DownstreamResumeRequest `protobuf:"bytes,130,opt,name=downstream_resume_request,json=downstreamResumeRequest,proto3,oneof" json:"downstream_resume_request,omitempty"`
}
type Message_DownstreamResumeResponse struct {
	DownstreamResumeResponse *DownstreamResumeResponse `protobuf:"bytes,131,opt,name=downstream_resume_response,json=downstreamResumeResponse,proto3,oneof" json:"downstream_resume_response,omitempty"`
}
type Message_DownstreamCloseRequest struct {
	DownstreamCloseRequest *DownstreamCloseRequest `protobuf:"bytes,132,opt,name=downstream_close_request,json=downstreamCloseRequest,proto3,oneof" json:"downstream_close_request,omitempty"`
}
type Message_DownstreamCloseResponse struct {
	DownstreamCloseResponse *DownstreamCloseResponse `protobuf:"bytes,133,opt,name=downstream_close_response,json=downstreamCloseResponse,proto3,oneof" json:"downstream_close_response,omitempty"`
}
type Message_DownstreamChunk struct {
	DownstreamChunk *DownstreamChunk `protobuf:"bytes,134,opt,name=downstream_chunk,json=downstreamChunk,proto3,oneof" json:"downstream_chunk,omitempty"`
}
type Message_DownstreamChunkAck struct {
	DownstreamChunkAck *DownstreamChunkAck `protobuf:"bytes,135,opt,name=downstream_chunk_ack,json=downstreamChunkAck,proto3,oneof" json:"downstream_chunk_ack,omitempty"`
}
type Message_DownstreamChunkAckComplete struct {
	DownstreamChunkAckComplete *DownstreamChunkAckComplete `protobuf:"bytes,136,opt,name=downstream_chunk_ack_complete,json=downstreamChunkAckComplete,proto3,oneof" json:"downstream_chunk_ack_complete,omitempty"`
}
type Message_DownstreamMetadata struct {
	DownstreamMetadata *DownstreamMetadata `protobuf:"bytes,137,opt,name=downstream_metadata,json=downstreamMetadata,proto3,oneof" json:"downstream_metadata,omitempty"`
}
type Message_DownstreamMetadataAck struct {
	DownstreamMetadataAck *DownstreamMetadataAck `protobuf:"bytes,138,opt,name=downstream_metadata_ack,json=downstreamMetadataAck,proto3,oneof" json:"downstream_metadata_ack,omitempty"`
}
type Message_Ping struct {
	Ping *Ping `protobuf:"bytes,192,opt,name=ping,proto3,oneof" json:"ping,omitempty"`
}
type Message_Pong struct {
	Pong *Pong `protobuf:"bytes,193,opt,name=pong,proto3,oneof" json:"pong,omitempty"`
}
type Message_UpstreamCall struct {
	UpstreamCall *UpstreamCall `protobuf:"bytes,256,opt,name=upstream_call,json=upstreamCall,proto3,oneof" json:"upstream_call,omitempty"`
}
type Message_UpstreamCallAck struct {
	UpstreamCallAck *UpstreamCallAck `protobuf:"bytes,257,opt,name=upstream_call_ack,json=upstreamCallAck,proto3,oneof" json:"upstream_call_ack,omitempty"`
}
type Message_DownstreamCall struct {
	DownstreamCall *DownstreamCall `protobuf:"bytes,258,opt,name=downstream_call,json=downstreamCall,proto3,oneof" json:"downstream_call,omitempty"`
}

func (*Message_ConnectRequest) isMessage_Message()             {}
func (*Message_ConnectResponse) isMessage_Message()            {}
func (*Message_Disconnect) isMessage_Message()                 {}
func (*Message_UpstreamOpenRequest) isMessage_Message()        {}
func (*Message_UpstreamOpenResponse) isMessage_Message()       {}
func (*Message_UpstreamResumeRequest) isMessage_Message()      {}
func (*Message_UpstreamResumeResponse) isMessage_Message()     {}
func (*Message_UpstreamCloseRequest) isMessage_Message()       {}
func (*Message_UpstreamCloseResponse) isMessage_Message()      {}
func (*Message_UpstreamChunk) isMessage_Message()              {}
func (*Message_UpstreamChunkAck) isMessage_Message()           {}
func (*Message_UpstreamMetadata) isMessage_Message()           {}
func (*Message_UpstreamMetadataAck) isMessage_Message()        {}
func (*Message_DownstreamOpenRequest) isMessage_Message()      {}
func (*Message_DownstreamOpenResponse) isMessage_Message()     {}
func (*Message_DownstreamResumeRequest) isMessage_Message()    {}
func (*Message_DownstreamResumeResponse) isMessage_Message()   {}
func (*Message_DownstreamCloseRequest) isMessage_Message()     {}
func (*Message_DownstreamCloseResponse) isMessage_Message()    {}
func (*Message_DownstreamChunk) isMessage_Message()            {}
func (*Message_DownstreamChunkAck) isMessage_Message()         {}
func (*Message_DownstreamChunkAckComplete) isMessage_Message() {}
func (*Message_DownstreamMetadata) isMessage_Message()         {}
func (*Message_DownstreamMetadataAck) isMessage_Message()      {}
func (*Message_Ping) isMessage_Message()                       {}
func (*Message_Pong) isMessage_Message()                       {}
func (*Message_UpstreamCall) isMessage_Message()               {}
func (*Message_UpstreamCallAck) isMessage_Message()            {}
func (*Message_DownstreamCall) isMessage_Message()             {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetConnectRequest() *ConnectRequest {
	if x, ok := m.GetMessage().(*Message_ConnectRequest); ok {
		return x.ConnectRequest
	}
	return nil
}

func (m *Message) GetConnectResponse() *ConnectResponse {
	if x, ok := m.GetMessage().(*Message_ConnectResponse); ok {
		return x.ConnectResponse
	}
	return nil
}

func (m *Message) GetDisconnect() *Disconnect {
	if x, ok := m.GetMessage().(*Message_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

func (m *Message) GetUpstreamOpenRequest() *UpstreamOpenRequest {
	if x, ok := m.GetMessage().(*Message_UpstreamOpenRequest); ok {
		return x.UpstreamOpenRequest
	}
	return nil
}

func (m *Message) GetUpstreamOpenResponse() *UpstreamOpenResponse {
	if x, ok := m.GetMessage().(*Message_UpstreamOpenResponse); ok {
		return x.UpstreamOpenResponse
	}
	return nil
}

func (m *Message) GetUpstreamResumeRequest() *UpstreamResumeRequest {
	if x, ok := m.GetMessage().(*Message_UpstreamResumeRequest); ok {
		return x.UpstreamResumeRequest
	}
	return nil
}

func (m *Message) GetUpstreamResumeResponse() *UpstreamResumeResponse {
	if x, ok := m.GetMessage().(*Message_UpstreamResumeResponse); ok {
		return x.UpstreamResumeResponse
	}
	return nil
}

func (m *Message) GetUpstreamCloseRequest() *UpstreamCloseRequest {
	if x, ok := m.GetMessage().(*Message_UpstreamCloseRequest); ok {
		return x.UpstreamCloseRequest
	}
	return nil
}

func (m *Message) GetUpstreamCloseResponse() *UpstreamCloseResponse {
	if x, ok := m.GetMessage().(*Message_UpstreamCloseResponse); ok {
		return x.UpstreamCloseResponse
	}
	return nil
}

func (m *Message) GetUpstreamChunk() *UpstreamChunk {
	if x, ok := m.GetMessage().(*Message_UpstreamChunk); ok {
		return x.UpstreamChunk
	}
	return nil
}

func (m *Message) GetUpstreamChunkAck() *UpstreamChunkAck {
	if x, ok := m.GetMessage().(*Message_UpstreamChunkAck); ok {
		return x.UpstreamChunkAck
	}
	return nil
}

func (m *Message) GetUpstreamMetadata() *UpstreamMetadata {
	if x, ok := m.GetMessage().(*Message_UpstreamMetadata); ok {
		return x.UpstreamMetadata
	}
	return nil
}

func (m *Message) GetUpstreamMetadataAck() *UpstreamMetadataAck {
	if x, ok := m.GetMessage().(*Message_UpstreamMetadataAck); ok {
		return x.UpstreamMetadataAck
	}
	return nil
}

func (m *Message) GetDownstreamOpenRequest() *DownstreamOpenRequest {
	if x, ok := m.GetMessage().(*Message_DownstreamOpenRequest); ok {
		return x.DownstreamOpenRequest
	}
	return nil
}

func (m *Message) GetDownstreamOpenResponse() *DownstreamOpenResponse {
	if x, ok := m.GetMessage().(*Message_DownstreamOpenResponse); ok {
		return x.DownstreamOpenResponse
	}
	return nil
}

func (m *Message) GetDownstreamResumeRequest() *DownstreamResumeRequest {
	if x, ok := m.GetMessage().(*Message_DownstreamResumeRequest); ok {
		return x.DownstreamResumeRequest
	}
	return nil
}

func (m *Message) GetDownstreamResumeResponse() *DownstreamResumeResponse {
	if x, ok := m.GetMessage().(*Message_DownstreamResumeResponse); ok {
		return x.DownstreamResumeResponse
	}
	return nil
}

func (m *Message) GetDownstreamCloseRequest() *DownstreamCloseRequest {
	if x, ok := m.GetMessage().(*Message_DownstreamCloseRequest); ok {
		return x.DownstreamCloseRequest
	}
	return nil
}

func (m *Message) GetDownstreamCloseResponse() *DownstreamCloseResponse {
	if x, ok := m.GetMessage().(*Message_DownstreamCloseResponse); ok {
		return x.DownstreamCloseResponse
	}
	return nil
}

func (m *Message) GetDownstreamChunk() *DownstreamChunk {
	if x, ok := m.GetMessage().(*Message_DownstreamChunk); ok {
		return x.DownstreamChunk
	}
	return nil
}

func (m *Message) GetDownstreamChunkAck() *DownstreamChunkAck {
	if x, ok := m.GetMessage().(*Message_DownstreamChunkAck); ok {
		return x.DownstreamChunkAck
	}
	return nil
}

func (m *Message) GetDownstreamChunkAckComplete() *DownstreamChunkAckComplete {
	if x, ok := m.GetMessage().(*Message_DownstreamChunkAckComplete); ok {
		return x.DownstreamChunkAckComplete
	}
	return nil
}

func (m *Message) GetDownstreamMetadata() *DownstreamMetadata {
	if x, ok := m.GetMessage().(*Message_DownstreamMetadata); ok {
		return x.DownstreamMetadata
	}
	return nil
}

func (m *Message) GetDownstreamMetadataAck() *DownstreamMetadataAck {
	if x, ok := m.GetMessage().(*Message_DownstreamMetadataAck); ok {
		return x.DownstreamMetadataAck
	}
	return nil
}

func (m *Message) GetPing() *Ping {
	if x, ok := m.GetMessage().(*Message_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *Message) GetPong() *Pong {
	if x, ok := m.GetMessage().(*Message_Pong); ok {
		return x.Pong
	}
	return nil
}

func (m *Message) GetUpstreamCall() *UpstreamCall {
	if x, ok := m.GetMessage().(*Message_UpstreamCall); ok {
		return x.UpstreamCall
	}
	return nil
}

func (m *Message) GetUpstreamCallAck() *UpstreamCallAck {
	if x, ok := m.GetMessage().(*Message_UpstreamCallAck); ok {
		return x.UpstreamCallAck
	}
	return nil
}

func (m *Message) GetDownstreamCall() *DownstreamCall {
	if x, ok := m.GetMessage().(*Message_DownstreamCall); ok {
		return x.DownstreamCall
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_ConnectRequest)(nil),
		(*Message_ConnectResponse)(nil),
		(*Message_Disconnect)(nil),
		(*Message_UpstreamOpenRequest)(nil),
		(*Message_UpstreamOpenResponse)(nil),
		(*Message_UpstreamResumeRequest)(nil),
		(*Message_UpstreamResumeResponse)(nil),
		(*Message_UpstreamCloseRequest)(nil),
		(*Message_UpstreamCloseResponse)(nil),
		(*Message_UpstreamChunk)(nil),
		(*Message_UpstreamChunkAck)(nil),
		(*Message_UpstreamMetadata)(nil),
		(*Message_UpstreamMetadataAck)(nil),
		(*Message_DownstreamOpenRequest)(nil),
		(*Message_DownstreamOpenResponse)(nil),
		(*Message_DownstreamResumeRequest)(nil),
		(*Message_DownstreamResumeResponse)(nil),
		(*Message_DownstreamCloseRequest)(nil),
		(*Message_DownstreamCloseResponse)(nil),
		(*Message_DownstreamChunk)(nil),
		(*Message_DownstreamChunkAck)(nil),
		(*Message_DownstreamChunkAckComplete)(nil),
		(*Message_DownstreamMetadata)(nil),
		(*Message_DownstreamMetadataAck)(nil),
		(*Message_Ping)(nil),
		(*Message_Pong)(nil),
		(*Message_UpstreamCall)(nil),
		(*Message_UpstreamCallAck)(nil),
		(*Message_DownstreamCall)(nil),
	}
}

func init() {
	proto.RegisterType((*Message)(nil), "iscp2.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x96, 0x4d, 0x53, 0xd3, 0x4e,
	0x1c, 0xc7, 0x13, 0xfe, 0x0f, 0x8c, 0x8b, 0xb4, 0x65, 0x4b, 0x69, 0xa8, 0x12, 0x91, 0x93, 0x17,
	0xcb, 0x0c, 0x1c, 0x1d, 0x67, 0x80, 0x16, 0x88, 0x07, 0x94, 0x89, 0xa3, 0x8e, 0xce, 0x38, 0x35,
	0x24, 0x6b, 0xe8, 0x90, 0x66, 0x63, 0x93, 0x1d, 0xaf, 0x80, 0xcf, 0xbe, 0x12, 0x5f, 0x82, 0x47,
	0xbc, 0x71, 0xf4, 0x25, 0x40, 0x5f, 0x85, 0x47, 0xa7, 0xbb, 0xdb, 0x64, 0x77, 0xbb, 0xb9, 0xb1,
	0xbf, 0x87, 0x0f, 0xdf, 0xfd, 0x65, 0xbf, 0xdb, 0x05, 0xf3, 0x03, 0x94, 0xa6, 0x5e, 0x88, 0xda,
	0xc9, 0x10, 0x67, 0x18, 0xfe, 0xd7, 0x4f, 0xfd, 0x64, 0xa3, 0x55, 0xf3, 0x71, 0x1c, 0x23, 0x3f,
	0xeb, 0xe3, 0x98, 0x25, 0x5a, 0xb5, 0x00, 0xbf, 0x8f, 0xd3, 0x6c, 0x88, 0xbc, 0x01, 0x8f, 0x54,
	0xd0, 0x06, 0xea, 0xf9, 0x5e, 0x14, 0xf1, 0x75, 0x35, 0xe9, 0xc7, 0x61, 0x2f, 0xc1, 0x71, 0x38,
	0x29, 0x20, 0x89, 0xd4, 0x70, 0x3f, 0xec, 0x67, 0xc7, 0xe4, 0xa8, 0xed, 0xe3, 0xc1, 0x7a, 0x88,
	0x43, 0xbc, 0x4e, 0xc3, 0x47, 0xe4, 0x2d, 0x5d, 0xd1, 0x05, 0xfd, 0x8b, 0x95, 0xaf, 0x5d, 0x2d,
	0x80, 0xd9, 0x03, 0x26, 0x0e, 0x6e, 0x81, 0x2a, 0x57, 0xd4, 0x1b, 0xa2, 0x77, 0x04, 0xa5, 0x99,
	0x65, 0xae, 0x9a, 0xf7, 0xe6, 0x36, 0x1a, 0x6d, 0x2a, 0xb8, 0xdd, 0x61, 0x59, 0x97, 0x25, 0x1d,
	0xc3, 0xad, 0xf8, 0x52, 0x04, 0x76, 0x40, 0xad, 0x20, 0xa4, 0x09, 0x8e, 0x53, 0x64, 0xcd, 0x50,
	0xc4, 0x92, 0x8a, 0x60, 0x59, 0xc7, 0x70, 0xab, 0xbe, 0x1c, 0x82, 0x9b, 0x00, 0x04, 0xfd, 0x94,
	0x47, 0xad, 0x7f, 0x68, 0xfb, 0x02, 0x6f, 0xef, 0xe6, 0x09, 0xc7, 0x70, 0x85, 0x32, 0x78, 0x08,
	0x1a, 0x93, 0x41, 0xf4, 0x70, 0x82, 0xe2, 0x7c, 0x07, 0x5b, 0xb4, 0xbf, 0xc5, 0xfb, 0x9f, 0xf1,
	0x9a, 0x27, 0x09, 0x8a, 0x8b, 0x6d, 0xd4, 0xc9, 0x74, 0x18, 0x3e, 0x05, 0x4b, 0x2a, 0x91, 0xef,
	0x68, 0x9b, 0x22, 0x6f, 0x69, 0x91, 0xf9, 0xb6, 0x16, 0x89, 0x26, 0x0e, 0x9f, 0x83, 0x66, 0x0e,
	0x1d, 0xa2, 0x94, 0x0c, 0x50, 0x2e, 0x74, 0x87, 0x52, 0x6f, 0x2b, 0x54, 0x97, 0x16, 0x15, 0x52,
	0xf3, 0x5d, 0x4a, 0x09, 0xf8, 0x12, 0x58, 0xd3, 0x5c, 0x2e, 0xb7, 0x43, 0xc1, 0x2b, 0x25, 0xe0,
	0x5c, 0xf0, 0x12, 0xd1, 0x66, 0xa4, 0x39, 0xf8, 0x11, 0x4e, 0x0b, 0xc5, 0x5d, 0xed, 0x1c, 0x3a,
	0xe3, 0x9a, 0x42, 0x70, 0x3e, 0x07, 0x31, 0x2e, 0xcd, 0x61, 0x02, 0xe5, 0x72, 0x77, 0xb5, 0x73,
	0xe0, 0xdd, 0xb9, 0xda, 0x06, 0xd1, 0x25, 0xe0, 0x43, 0x50, 0x29, 0xb8, 0xc7, 0x24, 0x3e, 0xb1,
	0xf6, 0x28, 0x6e, 0x51, 0xc5, 0x8d, 0x73, 0x8e, 0xe1, 0xce, 0x13, 0x31, 0x00, 0xf7, 0x01, 0x94,
	0xdb, 0x7b, 0x9e, 0x7f, 0x62, 0xed, 0x53, 0x44, 0x53, 0x87, 0xd8, 0xf6, 0xc7, 0x94, 0x1a, 0x51,
	0x62, 0x70, 0x0f, 0x2c, 0xe4, 0xa0, 0x01, 0xca, 0xbc, 0xc0, 0xcb, 0x3c, 0xcb, 0xd1, 0x72, 0x0e,
	0x78, 0x5a, 0xe4, 0x4c, 0x62, 0xd2, 0xb1, 0x9e, 0x70, 0xa8, 0xa6, 0x47, 0xda, 0x63, 0x3d, 0xe9,
	0x63, 0xb2, 0xea, 0x64, 0x3a, 0x0c, 0x5f, 0x80, 0x66, 0x71, 0xc9, 0xc8, 0x56, 0x39, 0x35, 0xa5,
	0xd1, 0x77, 0xf3, 0x32, 0xd9, 0x2d, 0x8d, 0x40, 0x97, 0x80, 0xaf, 0x80, 0x35, 0x0d, 0xe6, 0xdf,
	0xf4, 0xcc, 0x94, 0xce, 0xa0, 0x4a, 0x2e, 0xce, 0x60, 0xa0, 0xcd, 0xc0, 0xd7, 0x60, 0x59, 0x60,
	0x2b, 0xc6, 0x39, 0x67, 0x70, 0x7b, 0x0a, 0xae, 0x7a, 0x47, 0xd8, 0xb8, 0xec, 0x9e, 0x37, 0xa0,
	0xa5, 0xc3, 0x73, 0xf1, 0x1f, 0x18, 0xff, 0x4e, 0x29, 0x3f, 0x97, 0x6f, 0x05, 0x25, 0x39, 0x65,
	0x38, 0xb2, 0x8d, 0x3e, 0x96, 0x0d, 0x47, 0x71, 0x92, 0x30, 0x1c, 0xc9, 0x4b, 0xf2, 0x70, 0x14,
	0x37, 0x7d, 0x2a, 0x1b, 0x8e, 0x6a, 0xa8, 0x66, 0xa0, 0x4f, 0xc1, 0x2e, 0xa8, 0x89, 0x78, 0x6a,
	0xaa, 0xcf, 0xa6, 0x74, 0xa9, 0x0b, 0x54, 0xee, 0xab, 0x6a, 0x20, 0x87, 0xe0, 0x63, 0xb0, 0xa8,
	0x52, 0xe8, 0x39, 0xfe, 0xc2, 0x48, 0xcb, 0x7a, 0x12, 0x3b, 0xc7, 0x30, 0x98, 0x8a, 0xc2, 0x10,
	0xac, 0xe8, 0x78, 0x3d, 0x1f, 0x0f, 0x92, 0x08, 0x65, 0xc8, 0xfa, 0xca, 0xc0, 0x77, 0x4b, 0xc1,
	0x1d, 0x5e, 0xe9, 0x18, 0x6e, 0x2b, 0x28, 0xcd, 0xc2, 0x03, 0x50, 0x17, 0xfe, 0x51, 0xee, 0xe5,
	0x6f, 0x65, 0xba, 0x05, 0x3b, 0x0b, 0xba, 0x73, 0x43, 0xcb, 0xf6, 0x93, 0x2c, 0xfd, 0xbd, 0xcc,
	0x7e, 0xb2, 0xab, 0x1b, 0x81, 0x2e, 0x01, 0xd7, 0xc0, 0xbf, 0xe3, 0xa7, 0x81, 0x75, 0xc1, 0x28,
	0x73, 0x9c, 0x72, 0xd8, 0x8f, 0x43, 0xc7, 0x70, 0x69, 0x8e, 0xd6, 0xe0, 0x38, 0xb4, 0x7e, 0x29,
	0x35, 0x98, 0xd7, 0xe0, 0x38, 0x84, 0x0f, 0xc0, 0x7c, 0x71, 0x05, 0x7a, 0x51, 0x64, 0x9d, 0xb2,
	0x1f, 0xf0, 0xba, 0x7a, 0xfd, 0x79, 0x51, 0xe4, 0x18, 0xee, 0x4d, 0x22, 0xac, 0xe1, 0xae, 0x70,
	0xed, 0x8d, 0x9b, 0xe9, 0xbe, 0xce, 0xe4, 0x17, 0x80, 0x08, 0x60, 0x3b, 0xaa, 0x12, 0x39, 0x04,
	0xb7, 0x41, 0x55, 0xfc, 0xb8, 0x63, 0x15, 0xe7, 0x33, 0xd2, 0x4b, 0x44, 0xf8, 0x9c, 0x4c, 0x47,
	0x25, 0x90, 0x22, 0x3b, 0x37, 0xc0, 0x2c, 0x7f, 0x73, 0xed, 0xac, 0x5e, 0x5e, 0xdb, 0xc6, 0x9f,
	0x6b, 0xdb, 0xfc, 0x31, 0xb2, 0xcd, 0x9f, 0x23, 0xdb, 0xbc, 0x18, 0xd9, 0xe6, 0xe5, 0xc8, 0x36,
	0x7f, 0x8f, 0x6c, 0xf3, 0x6a, 0x64, 0x9b, 0x47, 0xff, 0xd3, 0xb7, 0xd0, 0xe6, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x47, 0xaf, 0xff, 0x26, 0xa7, 0x09, 0x00, 0x00,
}

func (this *Message) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message)
	if !ok {
		that2, ok := that.(Message)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.Message == nil {
		if this.Message != nil {
			return false
		}
	} else if this.Message == nil {
		return false
	} else if !this.Message.Equal(that1.Message) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Message_ConnectRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_ConnectRequest)
	if !ok {
		that2, ok := that.(Message_ConnectRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ConnectRequest.Equal(that1.ConnectRequest) {
		return false
	}
	return true
}
func (this *Message_ConnectResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_ConnectResponse)
	if !ok {
		that2, ok := that.(Message_ConnectResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ConnectResponse.Equal(that1.ConnectResponse) {
		return false
	}
	return true
}
func (this *Message_Disconnect) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_Disconnect)
	if !ok {
		that2, ok := that.(Message_Disconnect)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Disconnect.Equal(that1.Disconnect) {
		return false
	}
	return true
}
func (this *Message_UpstreamOpenRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamOpenRequest)
	if !ok {
		that2, ok := that.(Message_UpstreamOpenRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamOpenRequest.Equal(that1.UpstreamOpenRequest) {
		return false
	}
	return true
}
func (this *Message_UpstreamOpenResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamOpenResponse)
	if !ok {
		that2, ok := that.(Message_UpstreamOpenResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamOpenResponse.Equal(that1.UpstreamOpenResponse) {
		return false
	}
	return true
}
func (this *Message_UpstreamResumeRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamResumeRequest)
	if !ok {
		that2, ok := that.(Message_UpstreamResumeRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamResumeRequest.Equal(that1.UpstreamResumeRequest) {
		return false
	}
	return true
}
func (this *Message_UpstreamResumeResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamResumeResponse)
	if !ok {
		that2, ok := that.(Message_UpstreamResumeResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamResumeResponse.Equal(that1.UpstreamResumeResponse) {
		return false
	}
	return true
}
func (this *Message_UpstreamCloseRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamCloseRequest)
	if !ok {
		that2, ok := that.(Message_UpstreamCloseRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamCloseRequest.Equal(that1.UpstreamCloseRequest) {
		return false
	}
	return true
}
func (this *Message_UpstreamCloseResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamCloseResponse)
	if !ok {
		that2, ok := that.(Message_UpstreamCloseResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamCloseResponse.Equal(that1.UpstreamCloseResponse) {
		return false
	}
	return true
}
func (this *Message_UpstreamChunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamChunk)
	if !ok {
		that2, ok := that.(Message_UpstreamChunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamChunk.Equal(that1.UpstreamChunk) {
		return false
	}
	return true
}
func (this *Message_UpstreamChunkAck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamChunkAck)
	if !ok {
		that2, ok := that.(Message_UpstreamChunkAck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamChunkAck.Equal(that1.UpstreamChunkAck) {
		return false
	}
	return true
}
func (this *Message_UpstreamMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamMetadata)
	if !ok {
		that2, ok := that.(Message_UpstreamMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamMetadata.Equal(that1.UpstreamMetadata) {
		return false
	}
	return true
}
func (this *Message_UpstreamMetadataAck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamMetadataAck)
	if !ok {
		that2, ok := that.(Message_UpstreamMetadataAck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamMetadataAck.Equal(that1.UpstreamMetadataAck) {
		return false
	}
	return true
}
func (this *Message_DownstreamOpenRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamOpenRequest)
	if !ok {
		that2, ok := that.(Message_DownstreamOpenRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamOpenRequest.Equal(that1.DownstreamOpenRequest) {
		return false
	}
	return true
}
func (this *Message_DownstreamOpenResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamOpenResponse)
	if !ok {
		that2, ok := that.(Message_DownstreamOpenResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamOpenResponse.Equal(that1.DownstreamOpenResponse) {
		return false
	}
	return true
}
func (this *Message_DownstreamResumeRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamResumeRequest)
	if !ok {
		that2, ok := that.(Message_DownstreamResumeRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamResumeRequest.Equal(that1.DownstreamResumeRequest) {
		return false
	}
	return true
}
func (this *Message_DownstreamResumeResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamResumeResponse)
	if !ok {
		that2, ok := that.(Message_DownstreamResumeResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamResumeResponse.Equal(that1.DownstreamResumeResponse) {
		return false
	}
	return true
}
func (this *Message_DownstreamCloseRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamCloseRequest)
	if !ok {
		that2, ok := that.(Message_DownstreamCloseRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamCloseRequest.Equal(that1.DownstreamCloseRequest) {
		return false
	}
	return true
}
func (this *Message_DownstreamCloseResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamCloseResponse)
	if !ok {
		that2, ok := that.(Message_DownstreamCloseResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamCloseResponse.Equal(that1.DownstreamCloseResponse) {
		return false
	}
	return true
}
func (this *Message_DownstreamChunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamChunk)
	if !ok {
		that2, ok := that.(Message_DownstreamChunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamChunk.Equal(that1.DownstreamChunk) {
		return false
	}
	return true
}
func (this *Message_DownstreamChunkAck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamChunkAck)
	if !ok {
		that2, ok := that.(Message_DownstreamChunkAck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamChunkAck.Equal(that1.DownstreamChunkAck) {
		return false
	}
	return true
}
func (this *Message_DownstreamChunkAckComplete) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamChunkAckComplete)
	if !ok {
		that2, ok := that.(Message_DownstreamChunkAckComplete)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamChunkAckComplete.Equal(that1.DownstreamChunkAckComplete) {
		return false
	}
	return true
}
func (this *Message_DownstreamMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamMetadata)
	if !ok {
		that2, ok := that.(Message_DownstreamMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamMetadata.Equal(that1.DownstreamMetadata) {
		return false
	}
	return true
}
func (this *Message_DownstreamMetadataAck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamMetadataAck)
	if !ok {
		that2, ok := that.(Message_DownstreamMetadataAck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamMetadataAck.Equal(that1.DownstreamMetadataAck) {
		return false
	}
	return true
}
func (this *Message_Ping) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_Ping)
	if !ok {
		that2, ok := that.(Message_Ping)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Ping.Equal(that1.Ping) {
		return false
	}
	return true
}
func (this *Message_Pong) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_Pong)
	if !ok {
		that2, ok := that.(Message_Pong)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Pong.Equal(that1.Pong) {
		return false
	}
	return true
}
func (this *Message_UpstreamCall) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamCall)
	if !ok {
		that2, ok := that.(Message_UpstreamCall)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamCall.Equal(that1.UpstreamCall) {
		return false
	}
	return true
}
func (this *Message_UpstreamCallAck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_UpstreamCallAck)
	if !ok {
		that2, ok := that.(Message_UpstreamCallAck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamCallAck.Equal(that1.UpstreamCallAck) {
		return false
	}
	return true
}
func (this *Message_DownstreamCall) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message_DownstreamCall)
	if !ok {
		that2, ok := that.(Message_DownstreamCall)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.DownstreamCall.Equal(that1.DownstreamCall) {
		return false
	}
	return true
}
func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Message != nil {
		{
			size := m.Message.Size()
			i -= size
			if _, err := m.Message.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Message_ConnectRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_ConnectRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ConnectRequest != nil {
		{
			size, err := m.ConnectRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *Message_ConnectResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_ConnectResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ConnectResponse != nil {
		{
			size, err := m.ConnectResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *Message_Disconnect) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_Disconnect) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Disconnect != nil {
		{
			size, err := m.Disconnect.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamOpenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamOpenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamOpenRequest != nil {
		{
			size, err := m.UpstreamOpenRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamOpenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamOpenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamOpenResponse != nil {
		{
			size, err := m.UpstreamOpenResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0x8a
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamResumeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamResumeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamResumeRequest != nil {
		{
			size, err := m.UpstreamResumeRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0x92
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamResumeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamResumeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamResumeResponse != nil {
		{
			size, err := m.UpstreamResumeResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0x9a
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamCloseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamCloseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamCloseRequest != nil {
		{
			size, err := m.UpstreamCloseRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xa2
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamCloseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamCloseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamCloseResponse != nil {
		{
			size, err := m.UpstreamCloseResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xaa
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamChunk != nil {
		{
			size, err := m.UpstreamChunk.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamChunkAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamChunkAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamChunkAck != nil {
		{
			size, err := m.UpstreamChunkAck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xba
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamMetadata != nil {
		{
			size, err := m.UpstreamMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xc2
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamMetadataAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamMetadataAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamMetadataAck != nil {
		{
			size, err := m.UpstreamMetadataAck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xca
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamOpenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamOpenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamOpenRequest != nil {
		{
			size, err := m.DownstreamOpenRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamOpenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamOpenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamOpenResponse != nil {
		{
			size, err := m.DownstreamOpenResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0x8a
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamResumeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamResumeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamResumeRequest != nil {
		{
			size, err := m.DownstreamResumeRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0x92
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamResumeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamResumeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamResumeResponse != nil {
		{
			size, err := m.DownstreamResumeResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0x9a
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamCloseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamCloseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamCloseRequest != nil {
		{
			size, err := m.DownstreamCloseRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xa2
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamCloseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamCloseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamCloseResponse != nil {
		{
			size, err := m.DownstreamCloseResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xaa
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamChunk != nil {
		{
			size, err := m.DownstreamChunk.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xb2
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamChunkAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamChunkAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamChunkAck != nil {
		{
			size, err := m.DownstreamChunkAck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xba
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamChunkAckComplete) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamChunkAckComplete) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamChunkAckComplete != nil {
		{
			size, err := m.DownstreamChunkAckComplete.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xc2
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamMetadata != nil {
		{
			size, err := m.DownstreamMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xca
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamMetadataAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamMetadataAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamMetadataAck != nil {
		{
			size, err := m.DownstreamMetadataAck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x8
		i--
		dAtA[i] = 0xd2
	}
	return len(dAtA) - i, nil
}
func (m *Message_Ping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_Ping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Ping != nil {
		{
			size, err := m.Ping.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xc
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func (m *Message_Pong) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_Pong) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Pong != nil {
		{
			size, err := m.Pong.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xc
		i--
		dAtA[i] = 0x8a
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamCall != nil {
		{
			size, err := m.UpstreamCall.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x10
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func (m *Message_UpstreamCallAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_UpstreamCallAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UpstreamCallAck != nil {
		{
			size, err := m.UpstreamCallAck.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x10
		i--
		dAtA[i] = 0x8a
	}
	return len(dAtA) - i, nil
}
func (m *Message_DownstreamCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_DownstreamCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownstreamCall != nil {
		{
			size, err := m.DownstreamCall.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x10
		i--
		dAtA[i] = 0x92
	}
	return len(dAtA) - i, nil
}
func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedMessage(r randyMessage, easy bool) *Message {
	this := &Message{}
	oneofNumber_Message := []int32{1, 2, 3, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 192, 193, 256, 257, 258}[r.Intn(29)]
	switch oneofNumber_Message {
	case 1:
		this.Message = NewPopulatedMessage_ConnectRequest(r, easy)
	case 2:
		this.Message = NewPopulatedMessage_ConnectResponse(r, easy)
	case 3:
		this.Message = NewPopulatedMessage_Disconnect(r, easy)
	case 64:
		this.Message = NewPopulatedMessage_UpstreamOpenRequest(r, easy)
	case 65:
		this.Message = NewPopulatedMessage_UpstreamOpenResponse(r, easy)
	case 66:
		this.Message = NewPopulatedMessage_UpstreamResumeRequest(r, easy)
	case 67:
		this.Message = NewPopulatedMessage_UpstreamResumeResponse(r, easy)
	case 68:
		this.Message = NewPopulatedMessage_UpstreamCloseRequest(r, easy)
	case 69:
		this.Message = NewPopulatedMessage_UpstreamCloseResponse(r, easy)
	case 70:
		this.Message = NewPopulatedMessage_UpstreamChunk(r, easy)
	case 71:
		this.Message = NewPopulatedMessage_UpstreamChunkAck(r, easy)
	case 72:
		this.Message = NewPopulatedMessage_UpstreamMetadata(r, easy)
	case 73:
		this.Message = NewPopulatedMessage_UpstreamMetadataAck(r, easy)
	case 128:
		this.Message = NewPopulatedMessage_DownstreamOpenRequest(r, easy)
	case 129:
		this.Message = NewPopulatedMessage_DownstreamOpenResponse(r, easy)
	case 130:
		this.Message = NewPopulatedMessage_DownstreamResumeRequest(r, easy)
	case 131:
		this.Message = NewPopulatedMessage_DownstreamResumeResponse(r, easy)
	case 132:
		this.Message = NewPopulatedMessage_DownstreamCloseRequest(r, easy)
	case 133:
		this.Message = NewPopulatedMessage_DownstreamCloseResponse(r, easy)
	case 134:
		this.Message = NewPopulatedMessage_DownstreamChunk(r, easy)
	case 135:
		this.Message = NewPopulatedMessage_DownstreamChunkAck(r, easy)
	case 136:
		this.Message = NewPopulatedMessage_DownstreamChunkAckComplete(r, easy)
	case 137:
		this.Message = NewPopulatedMessage_DownstreamMetadata(r, easy)
	case 138:
		this.Message = NewPopulatedMessage_DownstreamMetadataAck(r, easy)
	case 192:
		this.Message = NewPopulatedMessage_Ping(r, easy)
	case 193:
		this.Message = NewPopulatedMessage_Pong(r, easy)
	case 256:
		this.Message = NewPopulatedMessage_UpstreamCall(r, easy)
	case 257:
		this.Message = NewPopulatedMessage_UpstreamCallAck(r, easy)
	case 258:
		this.Message = NewPopulatedMessage_DownstreamCall(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMessage(r, 259)
	}
	return this
}

func NewPopulatedMessage_ConnectRequest(r randyMessage, easy bool) *Message_ConnectRequest {
	this := &Message_ConnectRequest{}
	this.ConnectRequest = NewPopulatedConnectRequest(r, easy)
	return this
}
func NewPopulatedMessage_ConnectResponse(r randyMessage, easy bool) *Message_ConnectResponse {
	this := &Message_ConnectResponse{}
	this.ConnectResponse = NewPopulatedConnectResponse(r, easy)
	return this
}
func NewPopulatedMessage_Disconnect(r randyMessage, easy bool) *Message_Disconnect {
	this := &Message_Disconnect{}
	this.Disconnect = NewPopulatedDisconnect(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamOpenRequest(r randyMessage, easy bool) *Message_UpstreamOpenRequest {
	this := &Message_UpstreamOpenRequest{}
	this.UpstreamOpenRequest = NewPopulatedUpstreamOpenRequest(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamOpenResponse(r randyMessage, easy bool) *Message_UpstreamOpenResponse {
	this := &Message_UpstreamOpenResponse{}
	this.UpstreamOpenResponse = NewPopulatedUpstreamOpenResponse(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamResumeRequest(r randyMessage, easy bool) *Message_UpstreamResumeRequest {
	this := &Message_UpstreamResumeRequest{}
	this.UpstreamResumeRequest = NewPopulatedUpstreamResumeRequest(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamResumeResponse(r randyMessage, easy bool) *Message_UpstreamResumeResponse {
	this := &Message_UpstreamResumeResponse{}
	this.UpstreamResumeResponse = NewPopulatedUpstreamResumeResponse(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamCloseRequest(r randyMessage, easy bool) *Message_UpstreamCloseRequest {
	this := &Message_UpstreamCloseRequest{}
	this.UpstreamCloseRequest = NewPopulatedUpstreamCloseRequest(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamCloseResponse(r randyMessage, easy bool) *Message_UpstreamCloseResponse {
	this := &Message_UpstreamCloseResponse{}
	this.UpstreamCloseResponse = NewPopulatedUpstreamCloseResponse(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamChunk(r randyMessage, easy bool) *Message_UpstreamChunk {
	this := &Message_UpstreamChunk{}
	this.UpstreamChunk = NewPopulatedUpstreamChunk(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamChunkAck(r randyMessage, easy bool) *Message_UpstreamChunkAck {
	this := &Message_UpstreamChunkAck{}
	this.UpstreamChunkAck = NewPopulatedUpstreamChunkAck(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamMetadata(r randyMessage, easy bool) *Message_UpstreamMetadata {
	this := &Message_UpstreamMetadata{}
	this.UpstreamMetadata = NewPopulatedUpstreamMetadata(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamMetadataAck(r randyMessage, easy bool) *Message_UpstreamMetadataAck {
	this := &Message_UpstreamMetadataAck{}
	this.UpstreamMetadataAck = NewPopulatedUpstreamMetadataAck(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamOpenRequest(r randyMessage, easy bool) *Message_DownstreamOpenRequest {
	this := &Message_DownstreamOpenRequest{}
	this.DownstreamOpenRequest = NewPopulatedDownstreamOpenRequest(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamOpenResponse(r randyMessage, easy bool) *Message_DownstreamOpenResponse {
	this := &Message_DownstreamOpenResponse{}
	this.DownstreamOpenResponse = NewPopulatedDownstreamOpenResponse(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamResumeRequest(r randyMessage, easy bool) *Message_DownstreamResumeRequest {
	this := &Message_DownstreamResumeRequest{}
	this.DownstreamResumeRequest = NewPopulatedDownstreamResumeRequest(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamResumeResponse(r randyMessage, easy bool) *Message_DownstreamResumeResponse {
	this := &Message_DownstreamResumeResponse{}
	this.DownstreamResumeResponse = NewPopulatedDownstreamResumeResponse(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamCloseRequest(r randyMessage, easy bool) *Message_DownstreamCloseRequest {
	this := &Message_DownstreamCloseRequest{}
	this.DownstreamCloseRequest = NewPopulatedDownstreamCloseRequest(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamCloseResponse(r randyMessage, easy bool) *Message_DownstreamCloseResponse {
	this := &Message_DownstreamCloseResponse{}
	this.DownstreamCloseResponse = NewPopulatedDownstreamCloseResponse(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamChunk(r randyMessage, easy bool) *Message_DownstreamChunk {
	this := &Message_DownstreamChunk{}
	this.DownstreamChunk = NewPopulatedDownstreamChunk(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamChunkAck(r randyMessage, easy bool) *Message_DownstreamChunkAck {
	this := &Message_DownstreamChunkAck{}
	this.DownstreamChunkAck = NewPopulatedDownstreamChunkAck(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamChunkAckComplete(r randyMessage, easy bool) *Message_DownstreamChunkAckComplete {
	this := &Message_DownstreamChunkAckComplete{}
	this.DownstreamChunkAckComplete = NewPopulatedDownstreamChunkAckComplete(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamMetadata(r randyMessage, easy bool) *Message_DownstreamMetadata {
	this := &Message_DownstreamMetadata{}
	this.DownstreamMetadata = NewPopulatedDownstreamMetadata(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamMetadataAck(r randyMessage, easy bool) *Message_DownstreamMetadataAck {
	this := &Message_DownstreamMetadataAck{}
	this.DownstreamMetadataAck = NewPopulatedDownstreamMetadataAck(r, easy)
	return this
}
func NewPopulatedMessage_Ping(r randyMessage, easy bool) *Message_Ping {
	this := &Message_Ping{}
	this.Ping = NewPopulatedPing(r, easy)
	return this
}
func NewPopulatedMessage_Pong(r randyMessage, easy bool) *Message_Pong {
	this := &Message_Pong{}
	this.Pong = NewPopulatedPong(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamCall(r randyMessage, easy bool) *Message_UpstreamCall {
	this := &Message_UpstreamCall{}
	this.UpstreamCall = NewPopulatedUpstreamCall(r, easy)
	return this
}
func NewPopulatedMessage_UpstreamCallAck(r randyMessage, easy bool) *Message_UpstreamCallAck {
	this := &Message_UpstreamCallAck{}
	this.UpstreamCallAck = NewPopulatedUpstreamCallAck(r, easy)
	return this
}
func NewPopulatedMessage_DownstreamCall(r randyMessage, easy bool) *Message_DownstreamCall {
	this := &Message_DownstreamCall{}
	this.DownstreamCall = NewPopulatedDownstreamCall(r, easy)
	return this
}

type randyMessage interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMessage(r randyMessage) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMessage(r randyMessage) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneMessage(r)
	}
	return string(tmps)
}
func randUnrecognizedMessage(r randyMessage, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldMessage(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldMessage(dAtA []byte, r randyMessage, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateMessage(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateMessage(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Message != nil {
		n += m.Message.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Message_ConnectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConnectRequest != nil {
		l = m.ConnectRequest.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_ConnectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConnectResponse != nil {
		l = m.ConnectResponse.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_Disconnect) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Disconnect != nil {
		l = m.Disconnect.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamOpenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamOpenRequest != nil {
		l = m.UpstreamOpenRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamOpenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamOpenResponse != nil {
		l = m.UpstreamOpenResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamResumeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamResumeRequest != nil {
		l = m.UpstreamResumeRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamResumeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamResumeResponse != nil {
		l = m.UpstreamResumeResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamCloseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamCloseRequest != nil {
		l = m.UpstreamCloseRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamCloseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamCloseResponse != nil {
		l = m.UpstreamCloseResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamChunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamChunk != nil {
		l = m.UpstreamChunk.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamChunkAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamChunkAck != nil {
		l = m.UpstreamChunkAck.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamMetadata != nil {
		l = m.UpstreamMetadata.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamMetadataAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamMetadataAck != nil {
		l = m.UpstreamMetadataAck.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamOpenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamOpenRequest != nil {
		l = m.DownstreamOpenRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamOpenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamOpenResponse != nil {
		l = m.DownstreamOpenResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamResumeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamResumeRequest != nil {
		l = m.DownstreamResumeRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamResumeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamResumeResponse != nil {
		l = m.DownstreamResumeResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamCloseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamCloseRequest != nil {
		l = m.DownstreamCloseRequest.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamCloseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamCloseResponse != nil {
		l = m.DownstreamCloseResponse.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamChunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamChunk != nil {
		l = m.DownstreamChunk.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamChunkAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamChunkAck != nil {
		l = m.DownstreamChunkAck.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamChunkAckComplete) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamChunkAckComplete != nil {
		l = m.DownstreamChunkAckComplete.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamMetadata != nil {
		l = m.DownstreamMetadata.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamMetadataAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamMetadataAck != nil {
		l = m.DownstreamMetadataAck.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_Ping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ping != nil {
		l = m.Ping.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_Pong) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pong != nil {
		l = m.Pong.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamCall != nil {
		l = m.UpstreamCall.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_UpstreamCallAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UpstreamCallAck != nil {
		l = m.UpstreamCallAck.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}
func (m *Message_DownstreamCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownstreamCall != nil {
		l = m.DownstreamCall.Size()
		n += 2 + l + sovMessage(uint64(l))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConnectRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_ConnectRequest{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ConnectResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_ConnectResponse{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disconnect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Disconnect{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_Disconnect{v}
			iNdEx = postIndex
		case 64:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamOpenRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamOpenRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamOpenRequest{v}
			iNdEx = postIndex
		case 65:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamOpenResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamOpenResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamOpenResponse{v}
			iNdEx = postIndex
		case 66:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamResumeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamResumeRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamResumeRequest{v}
			iNdEx = postIndex
		case 67:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamResumeResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamResumeResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamResumeResponse{v}
			iNdEx = postIndex
		case 68:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamCloseRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamCloseRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamCloseRequest{v}
			iNdEx = postIndex
		case 69:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamCloseResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamCloseResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamCloseResponse{v}
			iNdEx = postIndex
		case 70:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamChunk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamChunk{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamChunk{v}
			iNdEx = postIndex
		case 71:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamChunkAck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamChunkAck{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamChunkAck{v}
			iNdEx = postIndex
		case 72:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamMetadata{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamMetadata{v}
			iNdEx = postIndex
		case 73:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamMetadataAck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamMetadataAck{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamMetadataAck{v}
			iNdEx = postIndex
		case 128:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamOpenRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamOpenRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamOpenRequest{v}
			iNdEx = postIndex
		case 129:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamOpenResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamOpenResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamOpenResponse{v}
			iNdEx = postIndex
		case 130:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamResumeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamResumeRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamResumeRequest{v}
			iNdEx = postIndex
		case 131:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamResumeResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamResumeResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamResumeResponse{v}
			iNdEx = postIndex
		case 132:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamCloseRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamCloseRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamCloseRequest{v}
			iNdEx = postIndex
		case 133:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamCloseResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamCloseResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamCloseResponse{v}
			iNdEx = postIndex
		case 134:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamChunk", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamChunk{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamChunk{v}
			iNdEx = postIndex
		case 135:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamChunkAck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamChunkAck{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamChunkAck{v}
			iNdEx = postIndex
		case 136:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamChunkAckComplete", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamChunkAckComplete{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamChunkAckComplete{v}
			iNdEx = postIndex
		case 137:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamMetadata{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamMetadata{v}
			iNdEx = postIndex
		case 138:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamMetadataAck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamMetadataAck{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamMetadataAck{v}
			iNdEx = postIndex
		case 192:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Ping{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_Ping{v}
			iNdEx = postIndex
		case 193:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pong", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Pong{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_Pong{v}
			iNdEx = postIndex
		case 256:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamCall", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamCall{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamCall{v}
			iNdEx = postIndex
		case 257:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpstreamCallAck", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UpstreamCallAck{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_UpstreamCallAck{v}
			iNdEx = postIndex
		case 258:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownstreamCall", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DownstreamCall{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Message = &Message_DownstreamCall{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
