// Code generated by MockGen. DO NOT EDIT.
// Source: ./transport.go
//
// Generated by this command:
//
//	mockgen -destination ./wiremock/transport.go -package wiremock -source ./transport.go
//

// Package wiremock is a generated GoMock package.
package wiremock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	message "github.com/aptpod/iscp-go/message"
	transport "github.com/aptpod/iscp-go/transport"
)

// MockEncodingTransport is a mock of EncodingTransport interface.
type MockEncodingTransport struct {
	ctrl     *gomock.Controller
	recorder *MockEncodingTransportMockRecorder
	isgomock struct{}
}

// MockEncodingTransportMockRecorder is the mock recorder for MockEncodingTransport.
type MockEncodingTransportMockRecorder struct {
	mock *MockEncodingTransport
}

// NewMockEncodingTransport creates a new mock instance.
func NewMockEncodingTransport(ctrl *gomock.Controller) *MockEncodingTransport {
	mock := &MockEncodingTransport{ctrl: ctrl}
	mock.recorder = &MockEncodingTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncodingTransport) EXPECT() *MockEncodingTransportMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEncodingTransport) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEncodingTransportMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEncodingTransport)(nil).Close))
}

// ReadMessage mocks base method.
func (m *MockEncodingTransport) ReadMessage() (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage")
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockEncodingTransportMockRecorder) ReadMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockEncodingTransport)(nil).ReadMessage))
}

// UnderlyingTransport mocks base method.
func (m *MockEncodingTransport) UnderlyingTransport() transport.ReadWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnderlyingTransport")
	ret0, _ := ret[0].(transport.ReadWriter)
	return ret0
}

// UnderlyingTransport indicates an expected call of UnderlyingTransport.
func (mr *MockEncodingTransportMockRecorder) UnderlyingTransport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnderlyingTransport", reflect.TypeOf((*MockEncodingTransport)(nil).UnderlyingTransport))
}

// WriteMessage mocks base method.
func (m *MockEncodingTransport) WriteMessage(arg0 message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessage indicates an expected call of WriteMessage.
func (mr *MockEncodingTransportMockRecorder) WriteMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessage", reflect.TypeOf((*MockEncodingTransport)(nil).WriteMessage), arg0)
}
