// Code generated by MockGen. DO NOT EDIT.
// Source: ./transport.go
//
// Generated by this command:
//
//	mockgen -destination ./wiremock/transport.go -package wiremock -source ./transport.go
//

// Package wiremock is a generated GoMock package.
package wiremock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	encoding "github.com/aptpod/iscp-go/encoding"
	message "github.com/aptpod/iscp-go/message"
	transport "github.com/aptpod/iscp-go/transport"
)

// MockEncodingTransport is a mock of EncodingTransport interface.
type MockEncodingTransport struct {
	ctrl     *gomock.Controller
	recorder *MockEncodingTransportMockRecorder
	isgomock struct{}
}

// MockEncodingTransportMockRecorder is the mock recorder for MockEncodingTransport.
type MockEncodingTransportMockRecorder struct {
	mock *MockEncodingTransport
}

// NewMockEncodingTransport creates a new mock instance.
func NewMockEncodingTransport(ctrl *gomock.Controller) *MockEncodingTransport {
	mock := &MockEncodingTransport{ctrl: ctrl}
	mock.recorder = &MockEncodingTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncodingTransport) EXPECT() *MockEncodingTransportMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEncodingTransport) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEncodingTransportMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEncodingTransport)(nil).Close))
}

// Read mocks base method.
func (m *MockEncodingTransport) Read() (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockEncodingTransportMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockEncodingTransport)(nil).Read))
}

// RxCount mocks base method.
func (m *MockEncodingTransport) RxCount() *encoding.Count {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RxCount")
	ret0, _ := ret[0].(*encoding.Count)
	return ret0
}

// RxCount indicates an expected call of RxCount.
func (mr *MockEncodingTransportMockRecorder) RxCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RxCount", reflect.TypeOf((*MockEncodingTransport)(nil).RxCount))
}

// RxMessageCounterValue mocks base method.
func (m *MockEncodingTransport) RxMessageCounterValue() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RxMessageCounterValue")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// RxMessageCounterValue indicates an expected call of RxMessageCounterValue.
func (mr *MockEncodingTransportMockRecorder) RxMessageCounterValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RxMessageCounterValue", reflect.TypeOf((*MockEncodingTransport)(nil).RxMessageCounterValue))
}

// TxCount mocks base method.
func (m *MockEncodingTransport) TxCount() *encoding.Count {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxCount")
	ret0, _ := ret[0].(*encoding.Count)
	return ret0
}

// TxCount indicates an expected call of TxCount.
func (mr *MockEncodingTransportMockRecorder) TxCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxCount", reflect.TypeOf((*MockEncodingTransport)(nil).TxCount))
}

// TxMessageCounterValue mocks base method.
func (m *MockEncodingTransport) TxMessageCounterValue() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxMessageCounterValue")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// TxMessageCounterValue indicates an expected call of TxMessageCounterValue.
func (mr *MockEncodingTransportMockRecorder) TxMessageCounterValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxMessageCounterValue", reflect.TypeOf((*MockEncodingTransport)(nil).TxMessageCounterValue))
}

// UnderlyingTransport mocks base method.
func (m *MockEncodingTransport) UnderlyingTransport() transport.ReadWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnderlyingTransport")
	ret0, _ := ret[0].(transport.ReadWriter)
	return ret0
}

// UnderlyingTransport indicates an expected call of UnderlyingTransport.
func (mr *MockEncodingTransportMockRecorder) UnderlyingTransport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnderlyingTransport", reflect.TypeOf((*MockEncodingTransport)(nil).UnderlyingTransport))
}

// Write mocks base method.
func (m *MockEncodingTransport) Write(arg0 message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockEncodingTransportMockRecorder) Write(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockEncodingTransport)(nil).Write), arg0)
}
